import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Header } from "@/components/header";
import { Providers } from "@/components/providers";
import { DotPattern } from "@/components/ui/dot-pattern";
import { cn } from "@/lib/utils";

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrains-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${jetbrainsMono.variable} antialiased`}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <main className="flex min-h-screen flex-1 flex-col px-8">
              {/* 主体背景 */}
              <DotPattern
                className={cn(
                  "mask-[radial-gradient(800px_circle_at_center,white,transparent)]"
                )}
              />

              <Header />

              {children}
            </main>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
